name: Build and Test
on:
  push:
    branches: [ master, scan ]
  pull_request:
    type: [ synchronize ]

jobs:
  stack-test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-cache-${{ hashFiles('./stack.yaml.lock') }}
        restore-keys: |
            ${{ runner.os }}-stack-cache-
    - name: Test
      run: stack build --no-nix
  trufflehog-scan:
    name: Trufflehog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: myob-ops/github-actions
          ref: main
          token: ${{ secrets.APPSEC_ACTIONS_TOKEN }}
          path: .github/actions
      - name: Trufflehog Actions Scan
        uses: ./.github/actions/trufflehog
        with:
          scanArguments: "--regex --entropy=False --rules /regex.json --max_depth=50 --branch=${{ github.ref }}"
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: myob-ops/github-actions
          ref: main
          token: ${{ secrets.APPSEC_ACTIONS_TOKEN }}
          path: .github/actions
      - uses: ./.github/actions/sonarscanner
        with:
          projectKey: 'sonar-platform-services:aws-lambda-oauth-extension'
          projectName: aws-lambda-oauth-extension
          login: ${{ secrets.SONARQUBE_TOKEN }}
