name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    type: [ synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Setup Dhall
      uses: dhall-lang/setup-dhall@v4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - uses: cachix/cachix-action@v10
      with:
        name: jcouyang
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: build
      run: nix-build static.nix
    - uses: actions/upload-artifact@v2
      with:
        name: aws-lambda-oauth-extension-x86_64-linux
        path: ./result/bin/aws-lambda-oauth-extension-exe
