name: Scan
on:
  push:
    branches: [ _todo_main ]

jobs:
  trufflehog-scan:
    name: Trufflehog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: myob-ops/github-actions
          ref: main
          token: ${{ secrets.APPSEC_ACTIONS_TOKEN }}
          path: .github/actions
      - name: Trufflehog Actions Scan
        uses: ./.github/actions/trufflehog
        with:
          scanArguments: "--regex --entropy=False --rules /regex.json --max_depth=50 --branch=${{ github.ref }}"
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: myob-ops/github-actions
          ref: main
          token: ${{ secrets.APPSEC_ACTIONS_TOKEN }}
          path: .github/actions
      - uses: ./.github/actions/sonarscanner
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          projectKey: 'sonar-platform-services:aws-lambda-oauth-extension'
          projectName: aws-lambda-oauth-extension
          login: ${{ secrets.SONARQUBE_TOKEN }}
